[Console]
icon = "console.png"
name = "Console"
script = "console_setup.py"
template = "pyaedt_console"

[ConsoleCLI]
icon = "console.png"
name = "PyAEDT CLI"
script = "cli_setup.py"
template = "pyaedt_cli"

[Jupyter]
icon = "console.png"
name = "Jupyter"
script = "jupyter_template.ipynb"
template = "jupyter"

[Run_Script]
icon = "run_script.png"
name = "Run PyAEDT Script"
script = ""
template = "run_pyaedt_script"

[ExtensionManager]
icon = "extension_manager.png"
name = "Extension Manager"
script = "extension_manager.py"
template = "run_extension_manager"

[VersionManager]
icon = "version_manager.png"
name = "Version Manager"
script = "version_manager.py"
template = "run_pyaedt_toolkit_script"

[GenerateReport] # All
name = "GenerateReport"
script = "create_report.py"
template = "run_pyaedt_toolkit_script"
