[AntennaWizard]
name = "Antenna Toolkit"
url = "https://aedt.antenna.toolkit.docs.pyansys.com/version/stable/getting_started/installation.html"

[PushfromTransient]
icon = "images/large/push.png"
name = "Push Excitation from transient data"
script = "push_excitation_from_file.py"
template = "run_pyaedt_toolkit_script"
url = "https://aedt.docs.pyansys.com/version/stable/User_guide/pyaedt_extensions_doc/hfss/push_excitation.html"

[ChokeDesigner]
icon = "images/large/choke.png"
name = "Choke Designer"
script = "choke_designer.py"
template = "run_pyaedt_toolkit_script"
url = "https://aedt.docs.pyansys.com/version/stable/User_guide/pyaedt_extensions_doc/hfss/choke_designer.html"

[ShieldingEffectiveness]
icon = "images/large/shielding.png"
name = "Shielding Effectiveness"
script = "shielding_effectiveness.py"
template = "run_pyaedt_toolkit_script"
url = "https://aedt.docs.pyansys.com/version/stable/User_guide/pyaedt_extensions_doc/hfss/shielding.html"

[ImportNastran] # HFSS, Icepak, HFSS 3D, Maxwell 3D, Q3D, Mechanical
icon = "../common/images/large/cad3d.png"
name = "Import Nastran/STL"
script = "../common/import_nastran.py"
template = "run_pyaedt_toolkit_script"
url = "https://aedt.docs.pyansys.com/version/stable/User_guide/pyaedt_extensions_doc/project/import_nastran.html"

[FieldsCalculator] # HFSS, Icepak, HFSS 3D, Maxwell 3D, Q3D, Maxwell 2D, Q2D, Mechanical
icon = "../common/images/large/fields.png"
name = "Advanced Fields Calculator"
script = "../common/advanced_fields_calculator.py"
template = "run_pyaedt_toolkit_script"
url = "https://aedt.docs.pyansys.com/version/stable/User_guide/pyaedt_extensions_doc/project/advanced_fields_calculator.html"

[PointCloudGenerator] # HFSS, Icepak, HFSS 3D, Maxwell 3D, Q3D, Mechanical, Maxwell 2D
icon = "../common/images/large/cloud.png"
name = "Point Cloud Generator"
script = "../common/points_cloud.py"
template = "run_pyaedt_toolkit_script"
url = "https://aedt.docs.pyansys.com/version/stable/User_guide/pyaedt_extensions_doc/project/point_cloud_generator.html"

[MoveIt]
icon = "images/large/move_it.png"
name = "Move It"
script = "move_it.py"
template = "run_pyaedt_toolkit_script"
url = "https://aedt.docs.pyansys.com/version/stable/User_guide/pyaedt_extensions_doc/hfss/move_it.html"

[MCADAssembly]
icon = "images/large/mcad_assembly.png"
name = "MCAD Assembly"
script = "mcad_assembly.py"
template = "run_pyaedt_toolkit_script"
url = "https://aedt.docs.pyansys.com/version/stable/User_guide/pyaedt_extensions_doc/hfss/mcad_assembly.html"
