[AntennaWizard]
name = "Antenna Toolkit"
url = "https://aedt.antenna.toolkit.docs.pyansys.com/version/stable/getting_started/installation.html"

[PushfromTransient]
name = "Push Excitation from transient data"
script = "push_excitation_from_file.py"
icon = "images/large/push.png"
template = "run_pyaedt_toolkit_script"
url= "https://aedt.docs.pyansys.com/version/stable/User_guide/pyaedt_extensions_doc/hfss/push_excitation.html"

[ChokeDesigner]
name = "Choke Designer"
script = "choke_designer.py"
icon = "images/large/choke.png"
template = "run_pyaedt_toolkit_script"
url = "https://aedt.docs.pyansys.com/version/stable/User_guide/pyaedt_extensions_doc/hfss/choke_designer.html"

[ShieldingEffectiveness]
name = "Shielding Effectiveness"
script = "shielding_effectiveness.py"
icon = "images/large/shielding.png"
template = "run_pyaedt_toolkit_script"
url = "https://aedt.docs.pyansys.com/version/stable/User_guide/pyaedt_extensions_doc/hfss/shielding.html"

[MoveIt]
name = "Move It"
script = "move_it.py"
icon = "images/large/move_it.png"
template = "run_pyaedt_toolkit_script"
url = "https://aedt.docs.pyansys.com/version/stable/User_guide/pyaedt_extensions_doc/hfss/move_it.html"

[MCADAssembly]
name = "MCAD Assembly"
script = "mcad_assembly.py"
icon = "images/large/mcad_assembly.png"
template = "run_pyaedt_toolkit_script"
url = "https://aedt.docs.pyansys.com/version/stable/User_guide/pyaedt_extensions_doc/hfss/mcad_assembly.html"


[Fresnel]
name = "Fresnel"
script = "fresnel.py"
icon = "images/large/fresnel.png"
template = "run_pyaedt_toolkit_script"
