[MagnetSegmentationWizard]
name = "Magnet Segmentation Toolkit"
url = "https://magnet.segmentation.toolkit.docs.pyansys.com/version/stable/getting_started/installation.html"

[ImportNastran] # HFSS, Icepak, HFSS 3D, Maxwell 3D, Q3D, Mechanical
icon = "../common/images/large/cad3d.png"
name = "Import Nastran/STL"
script = "../common/import_nastran.py"
template = "run_pyaedt_toolkit_script"
url = "https://aedt.docs.pyansys.com/version/stable/User_guide/pyaedt_extensions_doc/project/import_nastran.html"

[FieldsCalculator] # HFSS, Icepak, HFSS 3D, Maxwell 3D, Q3D, Maxwell 2D, Q2D, Mechanical
icon = "../common/images/large/fields.png"
name = "Advanced Fields Calculator"
script = "../common/advanced_fields_calculator.py"
template = "run_pyaedt_toolkit_script"
url = "https://aedt.docs.pyansys.com/version/stable/User_guide/pyaedt_extensions_doc/project/advanced_fields_calculator.html"

[PointCloudGenerator] # HFSS, Icepak, HFSS 3D, Maxwell 3D, Q3D, Mechanical, Maxwell 2D
icon = "../common/images/large/cloud.png"
name = "Point Cloud Generator"
script = "../common/points_cloud.py"
template = "run_pyaedt_toolkit_script"
url = "https://aedt.docs.pyansys.com/version/stable/User_guide/pyaedt_extensions_doc/project/point_cloud_generator.html"

[FieldsDistribution]
icon = "images/large/fields_distribution.png"
name = "Fields distribution"
script = "fields_distribution.py"
template = "run_pyaedt_toolkit_script"
url = "https://aedt.docs.pyansys.com/version/stable/User_guide/pyaedt_extensions_doc/maxwell/fields_distribution.html"

[CoilDesignGeometry]
icon = "images/large/coil.png"
name = "Create coil design geometry"
script = "create_coil.py"
template = "run_pyaedt_toolkit_script"
