[Export3D]
icon = "images/large/cad3d.png"
name = "Export to 3D"
script = "export_to_3d.py"
template = "run_pyaedt_toolkit_script"
url = "https://aedt.docs.pyansys.com/version/stable/User_guide/pyaedt_extensions_doc/hfss3dlayout/export_3d.html"

[PushfromTransient]
icon = "images/large/push.png"
name = "Push Excitation from transient data"
script = "push_excitation_from_file_3dl.py"
template = "run_pyaedt_toolkit_script"
url = "https://aedt.docs.pyansys.com/version/stable/User_guide/pyaedt_extensions_doc/hfss3dlayout/push_excitation.html"

[PointCloudGenerator] # HFSS, Icepak, HFSS 3D, Maxwell 3D, Q3D, Mechanical, Maxwell 2D
icon = "../common/images/large/cloud.png"
name = "Point Cloud Generator"
script = "../common/points_cloud.py"
template = "run_pyaedt_toolkit_script"
url = "https://aedt.docs.pyansys.com/version/stable/User_guide/pyaedt_extensions_doc/project/point_cloud_generator.html"

[ViaDesign]
icon = "images/large/via_design_icon.png"
name = "Via Design"
script = "via_design.py"
template = "run_pyaedt_toolkit_script"
url = "https://aedt.docs.pyansys.com/version/stable/User_guide/pyaedt_extensions_doc/project/via_design.html"

[ConfigureLayout]
icon = "images/large/aedb.png"
name = "Configure Layout"
script = "configure_layout.py"
template = "run_pyaedt_toolkit_script"
url = "https://aedt.docs.pyansys.com/version/stable/User_guide/pyaedt_extensions_doc/project/configure_layout.html"

[ExportFiles]
icon = "images/large/export.png"
name = "Export Layout info"
script = "export_layout.py"
template = "run_pyaedt_toolkit_script"
url = "https://aedt.docs.pyansys.com/version/stable/User_guide/pyaedt_extensions_doc/hfss3dlayout/export_layout.html"

[Cutout]
icon = "images/large/cutout.png"
name = "Advanced cutout"
script = "cutout.py"
template = "run_pyaedt_toolkit_script"
url = "https://aedt.docs.pyansys.com/version/stable/User_guide/pyaedt_extensions_doc/hfss3dlayout/cutout.html"

[Parametrize]
icon = "images/large/parametrize.png"
name = "Parametrize layout"
script = "parametrize_edb.py"
template = "run_pyaedt_toolkit_script"
url = "https://aedt.docs.pyansys.com/version/stable/User_guide/pyaedt_extensions_doc/hfss3dlayout/parametrize_edb.html"

[ArbitraryWaveport]
icon = "images/large/arbitrary_wave_port.png"
name = "Arbitrary Waveports"
script = "generate_arbitrary_wave_ports.py"
template = "run_pyaedt_toolkit_script"
url = "https://aedt.docs.pyansys.com/version/stable/User_guide/pyaedt_extensions_doc/hfss3dlayout/arbitrary_wave_port.html"

[ViaClustering]
icon = "images/large/via_merging.png"
name = "Via merging"
script = "via_clustering_extension.py"
template = "run_pyaedt_toolkit_script"

[PostLayoutDesignToolkit]
icon = "images/large/post_layout_design.png"
name = "Post Layout Design Toolkit"
script = "post_layout_design.py"
template = "run_pyaedt_toolkit_script"
url = "https://aedt.docs.pyansys.com/version/stable/User_guide/pyaedt_extensions_doc/hfss3dlayout/layout_design_toolkit.html"
