[Export3D]
name = "Export to 3D"
script = "export_to_3d.py"
icon = "images/large/cad3d.png"
template = "run_pyaedt_toolkit_script"

[PushfromTransient]
name = "Push Excitation from transient data"
script = "push_excitation_from_file_3dl.py"
icon = "images/large/push.png"
template = "run_pyaedt_toolkit_script"

[ExportFiles]
name = "Export Layout info"
script = "export_layout.py"
icon = "images/large/export.png"
template = "run_pyaedt_toolkit_script"

[Cutout]
name = "Advanced cutout"
script = "cutout.py"
icon = "images/large/cutout.png"
template = "run_pyaedt_toolkit_script"

[Parametrize]
name = "Parametrize layout"
script = "parametrize_edb.py"
icon = "images/large/parametrize.png"
template = "run_pyaedt_toolkit_script"

[ArbitraryWaveport]
name = "Arbitrary Waveports"
script = "generate_arbitrary_wave_ports.py"
icon = "images/large/arbitrary_wave_port.png"
template = "run_pyaedt_toolkit_script"

[ViaClustering]
name = "Via merging"
script = "via_clustering_extension.py"
icon = "images/large/via_merging.png"
template = "run_pyaedt_toolkit_script"

[PostLayoutDesignToolkit]
name = "Post Layout Design Toolkit"
script = "post_layout_design_toolkit.py"
icon = "images/large/post_layout_design_toolkit.png"
template = "run_pyaedt_toolkit_script"